### ISSUE TITLE
The universe is broken!

### ISSUE THREAD

**Issue by gstavrinos** [dsgou/annotator#2]
Now that the csvs can be read, the tool cannot open .bag files, due to an .avi conversion error. Changing some lines in the rosbagRGB.py file, the tool manages to write the .avi file, but cannot read it!!

Line 118 and forward, were changed to:

	height, width, bytesPerComponent, tmp = np.array(image_buffer[0]).shape
	
	video_writer = cv2.VideoWriter(rgbFileName, fourcc, framerate, (width,height), cv2.IMREAD_COLOR)
	
	if video_writer.isOpened():
		result = True
		i= 0

		image_buffer = np.delete(np.array(image_buffer[0]),-1,1)

Please take a look at the new .avi reading  method, since the problem should be creeping around there!

With lots of love,

George

**Comment by dsgou** [comment]
forgot to add rosbagVideo.py to commit 
rookie mistake :D, sorry for the inconvenience bro

**Comment by gstavrinos** [comment]
You are the awesomest!
